linters:
  enable:
    - deadcode
    - errcheck
    - goconst
    - gocritic
    - godot
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - revive
    - staticcheck
    - structcheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
run:
  deadline: 3m
  skip-dirs-use-default: true
  
  modules-download-mode: readonly

issues:
  max-issues-per-linter: 0

  max-same-issues: 0
